# This file contains the essential configs for the ingress controller helm chart

# Verbosity level of the App Gateway Ingress Controller
verbosityLevel: 3

################################################################################
# Specify which application gateway the ingress controller will manage
#
#
appgw:
    subscriptionId: ed8c06db-8633-49a0-8e3f-df0642c56aa5
    resourceGroup: bm-prod-rg
    name: bm-prod-aks-appgw
    usePrivateIP: false

    # Setting appgw.shared to "true" will create an AzureIngressProhibitedTarget CRD.
    # This prohibits AGIC from applying config for any host/path.
    # Use "kubectl get AzureIngressProhibitedTargets" to view and change this.
    shared: false

################################################################################
# Specify which kubernetes namespace the ingress controller will watch
# Default value is "default"
# Leaving this variable out or setting it to blank or empty string would
# result in Ingress Controller observing all acessible namespaces.
#
# kubernetes:
#   watchNamespace: <namespace>
#
################################################################################
# Specify the authentication with Azure Resource Manager
# Two authentication methods are available:
# - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
armAuth:
    type: aadPodIdentity
    identityResourceID: /subscriptions/ed8c06db-8633-49a0-8e3f-df0642c56aa5/resourcegroups/MC_bm-prod-rg_bm-prod-aks_northeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aad-cId
    identityClientID: c23719f7-b1a0-42b8-a0f3-2b74daee1a96

## Alternatively you can use Service Principal credentials
# armAuth:
#    type: servicePrincipal
#    secretJSON: <<Generate this value with: "az ad sp create-for-rbac --subscription <subscription-uuid> --sdk-auth | base64 -w0" >>

################################################################################
# Specify if the cluster is RBAC enabled or not
rbac:
    enabled: true # true/false

